### ISSUE TITLE
Version check failure causing large log error

### ISSUE THREAD

**Issue by DocterDum** [noeppi-noeppi/MythicBotany#94]
Failed version checks are dumping a large error to the console on game launch. It would be appreciated if these could be silenced or removed if possible.

Forge: 36.2.26
Mythic Botany:  1.4.19

[12:16:21] [Forge Version Check/INFO] [ne.mi.fm.VersionChecker/]: [mythicbotany] Starting version check at https://assets.melanx.de/updates/mythicbotany.json
[12:16:21] [Forge Version Check/WARN] [ne.mi.fm.VersionChecker/]: Failed to process update information
java.io.IOException: Server returned HTTP response code: 403 for URL: https://assets.melanx.de/updates/mythicbotany.json
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_322] {}
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_322] {}
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_322] {}
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1952) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1947) ~[?:1.8.0_322] {}
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1946) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1516) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:268) ~[?:1.8.0_322] {}
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:171) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.VersionChecker$1.process(VersionChecker.java:187) ~[forge:?] {re:classloading}
	at java.lang.Iterable.forEach(Iterable.java:75) [?:1.8.0_322] {}
	at net.minecraftforge.fml.VersionChecker$1.run(VersionChecker.java:139) [forge:?] {re:classloading}
Caused by: java.io.IOException: Server returned HTTP response code: 403 for URL: https://assets.melanx.de/updates/mythicbotany.json
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1902) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1500) ~[?:1.8.0_322] {}
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_322] {}
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352) ~[?:1.8.0_322] {}
	at net.minecraftforge.fml.VersionChecker$1.openUrlStream(VersionChecker.java:155) ~[forge:?] {re:classloading}
	... 3 more

**Comment by noeppi-noeppi** [comment]
the version is a forge feature. I have no control over the amount of logging that happens with the version checker. So the only way to fix it would be removing it entirely.
